[package]
name = "rust-performance-benchmarks"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[profile.release]
debug = true  # Keep debug symbols for profiling

[[bench]]
name = "memory_patterns"
harness = false